"""
APL - FastAPI Web Framework Library
Full FastAPI wrapper with Arabic keywords
"""

FASTAPI_FUNCS = {
    # إنشاء التطبيق (App Creation)
    "فاست_أبي": "FastAPI",
    "سريع": "FastAPI",
    "تطبيق_سريع": "FastAPI",
    "واجهة_سريعة": "FastAPI",
    "خدمة_سريعة": "FastAPI",
    "منصة_سريعة": "FastAPI",
    
    # المسارات (Routing)
    "مسار_جيت": "@app.get",
    "مسار_بوست": "@app.post",
    "مسار_حذف": "@app.delete",
    "مسار_تعديل": "@app.put",
    "مسار_تصحيح": "@app.patch",
    "مسار_خيارات": "@app.options",
    "مسار_رأس": "@app.head",
    "مسار_مسار": "@app.trace",
    "سريع_جيت": "@app.get",
    "سريع_بوست": "@app.post",
    "سريع_حذف": "@app.delete",
    "سريع_تعديل": "@app.put",
    "مسار_سريع": "@app.get",
    "رابط": "@app.get",
    "رابط_جيت": "@app.get",
    "رابط_بوست": "@app.post",
    "نقطة_نهاية": "@app.get",
    
    # تشغيل (Running)
    "شغل": "uvicorn.run",
    "شغل_خدمة": "uvicorn.run",
    "استمع": "uvicorn.run",
    "ابدأ": "uvicorn.run",
    "شغل_سريع": "uvicorn.run",
    
    # الطلب (Request)
    "طلب": "Request",
    "طلب_جسم": "request.json",
    "طلب_مسار": "request.path_params",
    "طلب_استعلام": "request.query_params",
    "طلب_رأس": "request.headers",
    "طلب_كوكي": "request.cookies",
    "طلب_جلسة": "request.session",
    "طلب_طريقة": "request.method",
    "طلب_عنوان": "request.url",
    "طلب_أي_بي": "request.client.host",
    "طلب_نموذج": "request.form",
    "طلب_ملف": "request.files",
    "طلب_مسار_كامل": "request.url.path",
    "طلب_نظامي": "request.url.params",
    "طلب_محلي": "request.url.hostname",
    
    # الاستجابة (Response)
    "استجابة": "Response",
    "استجابة_نص": "PlainTextResponse",
    "استجابة_جسون": "JSONResponse",
    "استجابة_توجيه": "RedirectResponse",
    "استجابة_ملف": "FileResponse",
    "استجابة_تدفق": "StreamingResponse",
    "استجابة_مباشرة": "UJSONResponse",
    "استجابة_بسيطة": "HTMLResponse",
    "استجابة_صفحة": "HTMLResponse",
    
    # نماذج البيانات (Data Models)
    "نموذج_أساسي": "BaseModel",
    "نموذج": "BaseModel",
    "نموذج_بيانات": "BaseModel",
    "نموذج_طلب": "BaseModel",
    "نموذج_استجابة": "BaseModel",
    "حقل": "Field",
    "حقل_مطلوب": "Field",
    "مدقق": "validator",
    "مسلسل": "jsonable_encoder",
    "إعدادات_النموذج": "model_config",
    
    # إعادة التوجيه (Redirect)
    "حول": "RedirectResponse",
    "إعادة_توجيه": "RedirectResponse",
    "رابط_دائم": "url_for",
    "بناء_رابط": "url_for",
    
    # القوالب (Templates)
    "عرض": "templates.TemplateResponse",
    "قالب": "templates.TemplateResponse",
    "عرض_قالب": "templates.TemplateResponse",
    "عرض_صفحة": "templates.TemplateResponse",
    
    # الأخطاء (Errors)
    "خطأ_ http": "HTTPException",
    "خطأ": "HTTPException",
    "خطأ_400": "HTTPException",
    "خطأ_401": "HTTPException",
    "خطأ_403": "HTTPException",
    "خطأ_404": "HTTPException",
    "خطأ_405": "HTTPException",
    "خطأ_408": "HTTPException",
    "خطأ_409": "HTTPException",
    "خطأ_422": "HTTPException",
    "خطأ_429": "HTTPException",
    "خطأ_500": "HTTPException",
    "خطأ_502": "HTTPException",
    "خطأ_503": "HTTPException",
    "خطأ_504": "HTTPException",
    "خطأ_بيانات": "RequestValidationError",
    "خطأ_تحقق": "RequestValidationError",
    "استثناء": "HTTPException",
    "استثناء_عام": "HTTPException",
    
    # الحالة (Status Codes)
    "نجاح": "status.HTTP_200_OK",
    "تم_إنشاء": "status.HTTP_201_CREATED",
    "مقبول": "status.HTTP_202_ACCEPTED",
    "بدون_محتوى": "status.HTTP_204_NO_CONTENT",
    "معدوم": "status.HTTP_301_MOVED_PERMANENTLY",
    "تم_إيجاده": "status.HTTP_302_FOUND",
    "معدل": "status.HTTP_304_NOT_MODIFIED",
    "طلب_سيء": "status.HTTP_400_BAD_REQUEST",
    "غير_مصرح": "status.HTTP_401_UNAUTHORIZED",
    "محظور": "status.HTTP_403_FORBIDDEN",
    "غير_موجود": "status.HTTP_404_NOT_FOUND",
    "غير_مسموح": "status.HTTP_405_METHOD_NOT_ALLOWED",
    "انتهت_مهلة": "status.HTTP_408_REQUEST_TIMEOUT",
    "تعارض": "status.HTTP_409_CONFLICT",
    "خطأ_خادم": "status.HTTP_500_INTERNAL_SERVER_ERROR",
    "غير_منفذ": "status.HTTP_501_NOT_IMPLEMENTED",
    "بوابة_سيئة": "status.HTTP_502_BAD_GATEWAY",
    "خدمة_غير_متوفرة": "status.HTTP_503_SERVICE_UNAVAILABLE",
    "مهلة_بوابة": "status.HTTP_504_GATEWAY_TIMEOUT",
    
    # التحقق من الصحة (Health Check)
    "فحص_صحة": "health",
    "صحة": "health",
    "فحص": "health",
    "حالة": "health",
    "حالة_الخدمة": "health",
    "حالة_النظام": "health",
    "حالة_قاعدة": "health",
    "حالة_اتصال": "health",
    
    # وسطاء (Middlewares)
    "وسيط": "middleware",
    "قبل_طلب": "middleware('http')",
    "بعد_طلب": "middleware('http')",
    "وسيط_طلب": "app.middleware('http')",
    "موجه_طلب": "app.middleware('http')",
    "مراقب": "app.middleware('http')",
    "مراقب_طلب": "app.middleware('http')",
    
    # التبعيات (Dependencies)
    "تبعية": "Depends",
    "تعتمد": "Depends",
    "تبعية_حقن": "Depends",
    "تبعية_جلسة": "Depends(get_db)",
    "حماية": "Depends(get_current_user",
    "تحقق_رمز": "Depends(oauth2_scheme)",
    "مصادقة": "Depends(get_current_active_user",
    "جلسة_قاعدة": "Depends(get_db)",
    "قاعدة_بيانات": "Depends(get_db)",
    "مستخدم_حالي": "Depends(get_current_user",
    "رمز_وصول": "Depends(oauth2_scheme)",
    
    # المصادقة (Auth)
    "سجل_دخول": "login_for_access_token",
    "سجل_خروج": "logout",
    "رمز_وصول": "create_access_token",
    "رمز_تحقق": "create_access_token",
    "رمز_جديد": "create_access_token",
    "تحقق_رمز": "verify_access_token",
    "تحقق_من": "get_current_user",
    "تحقق_مستخدم": "get_current_active_user",
    "شفر_كلمة": "get_password_hash",
    "تحقق_كلمة": "verify_password",
    "كلمة_مرور_صحيحة": "verify_password",
    "كلمة_مشروعة": "verify_password",
    "مصادقة_أساسية": "HTTPBasic",
    "مصادقة_رمز": "OAuth2PasswordBearer",
    "مصادقة_حامل": "OAuth2PasswordBearer",
    "نظام_مصادقة": "OAuth2PasswordBearer",
    "حماية_مسار": "Security",
    "حماية_متقدمة": "Security",
    "أدوار": "Security",
    "أذونات": "Security",
    
    # رفع الملفات (File Upload)
    "احفظ_ملف": "file.save",
    "ملف_آمن": "secure_filename",
    "اسم_آمن": "secure_filename",
    "ملف_مرفوع": "UploadFile",
    "ملف_صورة": "UploadFile",
    "ملف_صوت": "UploadFile",
    "ملف_فيديو": "UploadFile",
    "ملف_مستند": "UploadFile",
    "ملف_ثنائي": "UploadFile",
    "احفظ_ملفات": "files.save",
    "احفظ_صورة": "file.save",
    
    # CORS
    "كورس": "CORSMiddleware",
    "وصول_متبادل": "CORSMiddleware",
    "موارد_مشتركة": "CORSMiddleware",
    "أصل_متبادل": "CORSMiddleware",
    "رأس_متبادل": "CORSMiddleware",
    "طرق_متبادل": "CORSMiddleware",
    
    # الأحداث (Events)
    "عند_بدء": "app.on_event('startup')",
    "عند_إيقاف": "app.on_event('shutdown')",
    "حدث_بدء": "app.on_event('startup')",
    "حدث_إيقاف": "app.on_event('shutdown')",
    "حدث_جاهز": "app.on_event('startup')",
    "حدث_إغلاق": "app.on_event('shutdown')",
    "جاهز": "app.on_event('startup')",
    "إغلاق": "app.on_event('shutdown')",
    
    # الملفات الثابتة (Static Files)
    "ملفات_ثابتة": "StaticFiles",
    "ملف_ثابت": "StaticFiles.static_directory",
    "دليل_ثابت": "StaticFiles",
    "مسار_ثابت": "StaticFiles",
    "موارد_ثابتة": "StaticFiles",
    
    # التوثيق (Documentation)
    "توثيق": "docs",
    "توثيق_سريع": "docs",
    "توثيق_تفاعلي": "docs",
    "تجربة": "docs",
    "اختبار_تفاعلي": "docs",
    "مرجع": "docs",
    "مرجع_سريع": "docs",
    "وصف_خدمة": "docs",
    "مواصفات": "docs",
    "مواصفات_خدمة": "docs",
    "نقطة_مرجعية": "docs",
    "مساعدة": "docs",
    "دليل_سريع": "docs",
    "مرجع_تفاعلي": "docs",
    
    # اختبار (Testing)
    "اختبار_عميل": "TestClient",
    "عميل": "TestClient",
    "اختبار": "TestClient",
    "اختبار_خدمة": "TestClient",
    
    # قاعدة البيانات (Database)
    "جلسة_قاعدة": "SessionLocal",
    "قاعدة_محلية": "SessionLocal",
    "قاعدة_بيانات": "SessionLocal",
    "قاعدة": "SessionLocal",
    "استعلام": "db.query",
    "أضف_سجل": "db.add",
    "نفذ": "db.commit",
    "تراجع": "db.rollback",
    "أغلق": "db.close",
    "امسح": "db.flush",
    "احذف_سجل": "db.delete",
    "حدّث": "db.refresh",
    
    # الترحيلات (Migrations)
    "ترحيل": "alembic",
    "ترحيل_قاعدة": "alembic",
    "إنشاء_جداول": "Base.metadata.create_all",
    "هجرة": "Base.metadata.create_all",
    "ترحيل_أولي": "Base.metadata.create_all",
    "ترحيل_تراجع": "alembic downgrade",
    "ترحيل_ترقية": "alembic upgrade",
    
    # التخزين المؤقت (Caching)
    "كاش": "cache",
    "تخزين_مؤقت": "cache",
    "مفتاح_كاش": "cache_key",
    "فترة_كاش": "cache_ttl",
    "مسح_كاش": "cache_clear",
    
    # تحديد المعدل (Rate Limiting)
    "حد_معدل": "rate_limit",
    "معدل_طلبات": "rate_limit",
    "حد_طلبات": "rate_limit",
    "تقييد": "rate_limit",
    "حماية_حمل": "rate_limit",
    "حماية_زحام": "rate_limit",
    
    # رؤوس الاستجابة (Response Headers)
    "رأس_استجابة": "response.headers",
    "ضع_رأس": "response.headers.__setitem__",
    "أضف_رأس": "response.headers.__setitem__",
    "رأس_خاص": "response.headers",
    "رأس_أمان": "response.headers",
    
    # ملفات تعريف الارتباط (Cookies)
    "كوكي": "response.set_cookie",
    "ضع_كوكي": "response.set_cookie",
    "احذف_كوكي": "response.delete_cookie",
    "كوكي_آمن": "response.set_cookie",
    "كوكي_جلسة": "response.set_cookie",
    "كوكي_دائم": "response.set_cookie",
    "كوكي_مسار": "response.set_cookie",
    "كوكي_نطاق": "response.set_cookie",
    
    # الجلسة (Session)
    "جلسة": "session",
    "ضع_جلسة": "session.__setitem__",
    "احذف_جلسة": "session.pop",
    "مسح_جلسة": "session.clear",
    "مفتاح_جلسة": "session_key",
    "فترة_جلسة": "session_timeout",
    "جلسة_آمنة": "session",
    "جلسة_مشفرة": "session",
    
    # الرسائل (Messages)
    "رسالة": "Message",
    "رسالة_خطأ": "Message",
    "رسالة_نجاح": "Message",
    "رسالة_تحذير": "Message",
    "رسالة_معلومة": "Message",
    "إشعار": "Message",
    "إشعار_نجاح": "Message",
    "إشعار_خطأ": "Message",
    "تنبيه": "Message",
    "خطأ_حقل": "ErrorDetail",
    
    # التحقق (Validation)
    "تحقق": "validate",
    "تحقق_بيانات": "validate",
    "تحقق_نموذج": "validate",
    "تحقق_صحة": "validate",
    "تحقق_إدخال": "validate",
    "تحقق_طلب": "validate",
    "تحقق_استجابة": "validate",
    "مدقق_بيانات": "validator",
    "مدقق_حقل": "validator",
    "مدقق_نموذج": "validator",
    "خطأ_تحقق": "ValidationError",
    
    # التصفح (Pagination)
    "تصفح": "pagination",
    "صفحة": "page",
    "حجم_صفحة": "page_size",
    "حد_أقصى": "limit",
    "إزاحة": "offset",
    "ترتيب": "sort",
    "ترتيب_تصاعدي": "sort_asc",
    "ترتيب_تنازلي": "sort_desc",
    "بحث_نصي": "search",
    
    # الفلترة (Filtering)
    "فلتر": "filter",
    "فلتر_حقل": "filter",
    "فلتر_نطاق": "filter",
    "فلتر_تاريخ": "filter",
    "فلتر_قيمة": "filter",
    "بحث_متقدم": "search",
    
    # الأمان (Security)
    "تشفير": "encrypt",
    "فك_تشفير": "decrypt",
    "تجزئة": "hash",
    "ملح": "salt",
    "توقيع": "sign",
    "تحقق_توقيع": "verify",
    "مفتاح_سري": "secret_key",
    "خوارزمية": "algorithm",
    "مدة_انتهاء": "expire_minutes",
    "تشفير_متماثل": "symmetric",
    "تشفير_غير_متماثل": "asymmetric",
    "تشفير_نهاية_إلى_نهاية": "e2e",
    
    # المراقبة (Monitoring)
    "سجل": "log",
    "سجل_خطأ": "log_error",
    "سجل_طلب": "log_request",
    "سجل_استجابة": "log_response",
    "تتبع": "trace",
    "قياس": "metric",
    "مؤشر": "metric",
    "أداء": "performance",
    "وقت_استجابة": "response_time",
    "معدل_نجاح": "success_rate",
    "معدل_خطأ": "error_rate",
    
    # الإعدادات (Settings)
    "إعدادات": "settings",
    "تكوين": "config",
    "متغيرات": "env",
    "متغير_بيئة": "env",
    "بيئة": "environment",
    "وضع": "mode",
    "وضع_تطوير": "development",
    "وضع_إنتاج": "production",
    "وضع_اختبار": "testing",
    "وضع_مسبق": "staging",
    "إصدار": "version",
    "اسم_خدمة": "service_name",
    "منفذ_خدمة": "port",
    "مضيف": "host",
    "عنوان": "url",
    "عنوان_قاعدة": "database_url",
    "مفتاح_ api": "api_key",
    "مفتاح_عام": "public_key",
    "مفتاح_خاص": "private_key",
    
    # الخلفية (Background)
    "خلفية": "BackgroundTasks",
    "مهمة_خلفية": "BackgroundTasks.add_task",
    "مهمة": "BackgroundTasks.add_task",
    "جدولة": "scheduler",
    "جدولة_مهمة": "scheduler.add_job",
    "مهمة_مجدولة": "scheduler.add_job",
    "مهمة_متكررة": "scheduler.add_job",
    
    # الترقية (WebSocket)
    "ويب_سوكيت": "WebSocket",
    "اتصال_مباشر": "WebSocket",
    "مقبس": "WebSocket",
    "قناة": "WebSocket",
    "بث": "WebSocket",
    "رسائل_مباشرة": "WebSocket",
    "إرسال_مباشر": "WebSocket.send_text",
    "استقبال_مباشر": "WebSocket.receive_text",
    "غرفة_دردشة": "WebSocketRoom",
    "مجموعة_اتصال": "WebSocketManager",
    
    # الإشعارات (Notifications)
    "إشعار": "notification",
    "إشعار_بريد": "email_notification",
    "إشعار_دفع": "push_notification",
    "إشعار_رسالة": "sms_notification",
    "بريد": "email",
    "رسالة_بريد": "email_message",
    "أرسل_بريد": "send_email",
    "أرسل_رسالة": "send_sms",
    "أرسل_إشعار": "send_notification",
    
    # الدفع (Payments)
    "دفع": "payment",
    "معاملة": "transaction",
    "معاملة_دفع": "payment_transaction",
    "بوابة_دفع": "payment_gateway",
    "طريقة_دفع": "payment_method",
    "حالة_دفع": "payment_status",
    "دفع_ناجح": "payment_success",
    "دفع_فاشل": "payment_failed",
    "استرداد": "refund",
    "إلغاء_دفع": "cancel_payment",
    "تأكيد_دفع": "confirm_payment",
    "دفع_متكرر": "recurring_payment",
    "اشتراك": "subscription",
    "خطة_اشتراك": "subscription_plan",
    "فترة_اشتراك": "subscription_period",
    "تجديد_اشتراك": "renew_subscription",
    "إلغاء_اشتراك": "cancel_subscription",
    
    # الجدولة (Scheduling)
    "جدولة": "scheduler",
    "مهمة_مجدولة": "scheduled_task",
    "مهمة_متكررة": "recurring_task",
    "مهمة_مؤجلة": "delayed_task",
    "مهمة_يومية": "daily_task",
    "مهمة_أسبوعية": "weekly_task",
    "مهمة_شهرية": "monthly_task",
    "تكرار": "interval",
    "فترة_تكرار": "interval_seconds",
    "وقت_بدء": "start_time",
    "وقت_انتهاء": "end_time",
    
    # البريد الإلكتروني (Email)
    "بريد_إلكتروني": "email",
    "رسالة_بريد": "email_message",
    "أرسل_بريد": "send_email",
    "أكد_بريد": "verify_email",
    "رابط_تأكيد": "verification_link",
    "استعادة_كلمة": "password_reset",
    "رابط_استعادة": "reset_link",
    
    # الرسائل (SMS)
    "رسالة_نصية": "sms",
    "أرسل_رسالة": "send_sms",
    "أكد_رسالة": "verify_sms",
    "رمز_تأكيد": "verification_code",
    "رمز_تحقق": "otp",
    
    # الإشعارات (Push)
    "إشعار_دفع": "push_notification",
    "أرسل_إشعار": "send_push",
    "رمز_جهاز": "device_token",
    "منصة_جهاز": "device_platform",
    
    # التحميل (Upload)
    "تحميل": "upload",
    "رفع": "upload",
    "ملف_مرفوع": "UploadFile",
    "حجم_ملف": "file_size",
    "نوع_ملف": "file_type",
    "اسم_ملف": "filename",
    "مسار_ملف": "file_path",
    
    # التنزيل (Download)
    "تنزيل": "download",
    "تحميل_ملف": "download",
    "ملف_تحميل": "download",
    "تصدير": "export",
    "استيراد": "import",
    "استيراد_ملف": "import_file",
    "تصدير_ملف": "export_file",
    
    # الصور (Images)
    "صورة": "image",
    "صورة_مصغرة": "thumbnail",
    "حجم_صورة": "image_size",
    "أبعاد_صورة": "image_dimensions",
    "عرض_صورة": "image_width",
    "ارتفاع_صورة": "image_height",
    "نوع_صورة": "image_type",
    "جودة_صورة": "image_quality",
    "ضغط_صورة": "compress_image",
    "تغيير_حجم": "resize_image",
    "قص_صورة": "crop_image",
    "تدوير_صورة": "rotate_image",
    "انعكاس_صورة": "flip_image",
    "فلتر_صورة": "image_filter",
    
    # الفيديو (Video)
    "فيديو": "video",
    "مشغل_فيديو": "video_player",
    "مدة_فيديو": "video_duration",
    "أبعاد_فيديو": "video_dimensions",
    "معدل_بت": "bitrate",
    "إطارات": "frames",
    "دقة": "resolution",
    "دقة_عالية": "high_resolution",
    "دقة_منخفضة": "low_resolution",
    
    # الصوت (Audio)
    "صوت": "audio",
    "مشغل_صوت": "audio_player",
    "مدة_صوت": "audio_duration",
    "معدل_عينة": "sample_rate",
    "قنوات": "channels",
    "تنسيق_صوت": "audio_format",
    
    # التشفير (Encryption)
    "تشفير": "encryption",
    "مفتاح_تشفير": "encryption_key",
    "خوارزمية_تشفير": "encryption_algorithm",
    "متجه_ابتدائي": "iv",
    "وضع_تشفير": "encryption_mode",
    "حشو": "padding",
    "طول_مفتاح": "key_length",
    "تدفق": "stream",
    
    # الضغط (Compression)
    "ضغط": "compression",
    "خوارزمية_ضغط": "compression_algorithm",
    "مستوى_ضغط": "compression_level",
    "نسبة_ضغط": "compression_ratio",
    "فك_ضغط": "decompress",
    "أرشيف": "archive",
    "ملف_مضغوط": "compressed_file",
    
    # التحويل (Conversion)
    "تحويل": "conversion",
    "تحويل_تنسيق": "format_conversion",
    "تحويل_نوع": "type_conversion",
    "تحويل_ترميز": "encoding_conversion",
    "تحويل_وحدة": "unit_conversion",
    "تحويل_عملة": "currency_conversion",
    "تحويل_تاريخ": "date_conversion",
    "تحويل_وقت": "time_conversion",
    
    # التحليل (Analytics)
    "تحليل": "analytics",
    "إحصائيات": "statistics",
    "تقارير": "reports",
    "لوحة_تحكم": "dashboard",
    "مخطط": "chart",
    "رسم_بياني": "graph",
    "مؤشر": "metric",
    "أداء": "performance",
    "استخدام": "usage",
    "معدل": "rate",
    "نسبة": "percentage",
    "اتجاه": "trend",
    "تنبؤ": "prediction",
    
    # الذكاء الاصطناعي (AI)
    "ذكاء": "ai",
    "نموذج": "model",
    "تدريب": "training",
    "تنبؤ": "prediction",
    "تصنيف": "classification",
    "تصنيف_نص": "text_classification",
    "تصنيف_صورة": "image_classification",
    "كشف_كائن": "object_detection",
    "تجزئة": "segmentation",
    "توليد": "generation",
    "تلخيص": "summarization",
    "ترجمة": "translation",
    "تحليل_مشاعر": "sentiment_analysis",
    "تعرف_صوت": "speech_recognition",
    "توليد_نص": "text_generation",
    "توليد_صورة": "image_generation",
    "توليد_كود": "code_generation",
    "دردشة": "chat",
    "محادثة": "conversation",
    "سؤال_جواب": "qa",
    "بحث_دلالي": "semantic_search",
    "تضمين": "embedding",
    "متجه_دلالي": "vector_embedding",
    "قاعدة_متجهات": "vector_database",
    "تشابه": "similarity",
    "مسافة_مشتركة": "cosine_similarity",
    
    # البلوكتشين (Blockchain)
    "بلوكتشين": "blockchain",
    "كتلة": "block",
    "سلسلة_كتل": "blockchain",
    "معاملة": "transaction",
    "عقد": "contract",
    "عقد_ذكي": "smart_contract",
    "محفظة": "wallet",
    "عنوان_محفظة": "wallet_address",
    "رمز": "token",
    "عملة_رقمية": "cryptocurrency",
    "تجميد": "staking",
    "تعدين": "mining",
    "إجماع": "consensus",
    "دليل_عمل": "proof_of_work",
    "دليل_حصة": "proof_of_stake",
    
    # إنترنت الأشياء (IoT)
    "إنترنت_أشياء": "iot",
    "جهاز": "device",
    "مستشعر": "sensor",
    "مشغل": "actuator",
    "بوابة": "gateway",
    "بروتوكول": "protocol",
    "mqtt": "mqtt",
    "mqtt_وكيل": "mqtt_broker",
    "رسالة_ mqtt": "mqtt_message",
    "اشتراك": "subscription",
    "موضوع": "topic",
    
    # الحوسبة السحابية (Cloud)
    "سحابة": "cloud",
    "خدمة_سحابية": "cloud_service",
    "تخزين_سحابي": "cloud_storage",
    "حاوية": "container",
    "دوكر": "docker",
    "كوبرنيتيس": "kubernetes",
    "مجموعة": "cluster",
    "عقدة": "node",
    "موازن_حمل": "load_balancer",
    "شبكة": "network",
    "شبكة_افتراضية": "vpc",
    "مجموعة_أمان": "security_group",
    "قاعدة_بيانات_سحابية": "cloud_database",
    "ذاكرة_مؤقتة_سحابية": "cloud_cache",
    "طابور_رسائل": "message_queue",
    
    # الميكروسيرفيس (Microservices)
    "ميكروسيرفيس": "microservice",
    "خدمة_صغيرة": "microservice",
    "خدمة": "service",
    "سجل_خدمات": "service_registry",
    "بوابة_خدمة": "api_gateway",
    "اكتشاف_خدمة": "service_discovery",
    "تتبع_خدمة": "distributed_tracing",
    "سجل_تجميع": "log_aggregation",
    "مراقبة": "monitoring",
    "تنبيه": "alerting",
    "لوحة_مراقبة": "monitoring_dashboard",
}

FASTAPI_PATTERN = r"(?<!\w)(" + "|".join(sorted(FASTAPI_FUNCS.keys(), key=len, reverse=True)) + r")\s*\("

# Help text for CLI
FASTAPI_HELP = [
    "# === إنشاء التطبيق ===",
    "سريع()                  - إنشاء تطبيق FastAPI",
    "فاست_أبي()              - إنشاء تطبيق FastAPI",
    "تطبيق_سريع()            - إنشاء تطبيق سريع",
    "# === المسارات ===",
    "سريع_جيت('/path')       - مسار GET",
    "سريع_بوست('/path')      - مسار POST",
    "سريع_حذف('/path')       - مسار DELETE",
    "سريع_تعديل('/path')     - مسار PUT",
    "# === تشغيل الخادم ===",
    "شغل(app, منفذ)         - تشغيل الخادم",
    "# === النماذج ===",
    "نموذج_أساسي()           - نموذج بيانات أساسي",
    "حقل(افتراضي, وصف)       - حقل في النموذج",
    "# === الطلب ===",
    "طلب                       - كائن الطلب",
    "طلب_جسم()                - جسم الطلب JSON",
    "طلب_مسار(مفتاح)          - معاملات المسار",
    "# === الاستجابة ===",
    "استجابة(محتوى)          - إنشاء استجابة",
    "استجابة_جسون(بيانات)   - استجابة JSON",
    "# === الأخطاء ===",
    "خطأ(رمز, تفاصيل)       - إطلاق خطأ HTTP",
    "غير_موجود()              - خطأ 404",
    "# === الحالة ===",
    "نجاح                     - 200 OK",
    "غير_مصرح                - 401 Unauthorized",
    "غير_موجود               - 404 Not Found",
    "خطأ_خادم                - 500 Internal Server Error",
    "# === الأمان ===",
    "تبعية(دالة)            - تبعية حقن",
    "مصادقة_رمز(مخطط)       - مصادقة بالرمز",
    "شفر_كلمة(كلمة)         - تشفير كلمة مرور",
    "# === خلفية ===",
    "خلفية                     - مهام الخلفية",
    "مهمة(دالة, *حجج)       - إضافة مهمة",
    "# === WebSocket ===",
    "ويب_سوكيت()             - اتصال WebSocket",
    "أرسل(رسالة)             - إرسال رسالة",
]

IMPORT_NAME = "fastapi"
IMPORT_CHECK = "fastapi\."
IMPORT_STATEMENT = "from fastapi import FastAPI, APIRouter, Depends, HTTPException, status, Request, Response, BackgroundTasks, WebSocket, File, UploadFile, Security"
