"""
APL - Patterns & Constants
All regex patterns, type aliases, and transpilation mappings
"""

import re

# Type aliases - أنواع البيانات
TYPE_ALIASES = {
    "صحيح": "int", "نص": "str", "عشري": "float", "منطق": "bool",
    "قائمة": "list", "مجموعة": "tuple", "مصفوفة": "set",
    "قاموس": "dict", "بايت": "bytes",
}
_TYPE_PATTERN = re.compile("(" + "|".join(TYPE_ALIASES.keys()) + r")\s*\(")

# Inline functions - الدوال المضمنة
_INLINE_FUNCS = {"نطاق": "range", "طول": "len"}
_INLINE_FUNC_PATTERN = re.compile("(" + "|".join(_INLINE_FUNCS.keys()) + r")\s*\(")

# Method aliases - أسماء الدوال البديلة
_METHOD_ALIASES = {
    "تقسيم": "split", "أضف": "append", "ضم": "join",
    "عكس": "reverse", "فرز": "sort", "حذف": "pop",
    "نسخ": "copy", "عد": "count", "بحث": "index",
    "أزل": "remove", "وسع": "extend", "أدخل": "insert",
    "استبدال": "replace", "علوي": "upper", "سفلي": "lower",
    "بداية": "startswith", "نهاية": "endswith", "تقليم": "strip",
    "اتحاد": "union", "تقاطع": "intersection", "فرق": "difference",
}
_METHOD_PATTERN = re.compile(r"\." + "(" + "|".join(_METHOD_ALIASES.keys()) + r")\s*\(")

# Type names for isinstance()
_TYPE_NAMES = {
    "صحيح": "int", "نص": "str", "عشري": "float", "منطق": "bool",
    "قائمة": "list", "مجموعة": "tuple", "مصفوفة": "set",
    "قاموس": "dict", "بايت": "bytes",
}

# Constants - الثوابت
_CONSTANTS = {
    "صواب": "True", "خطأ": "False", "لا_شيء": "None",
    "ط": "math.pi", "ه": "math.e",
    "تاو": "math.tau", "لانهائي_موجب": "math.inf",
}
_CONSTANT_PATTERN = re.compile(r"(?<!\w)(" + "|".join(_CONSTANTS.keys()) + r")(?!\w)")

# Logical patterns - العوامل المنطقية
_LOGICAL_PATTERNS = [
    (re.compile(r"(?<!\w)و(?!\w)"), "and"),
    (re.compile(r"(?<!\w)أو(?!\w)"), "or"),
    (re.compile(r"(?<!\w)ليس(?!\w)"), "not"),
    (re.compile(r"(?<!\w)مثل(?!\w)"), "as"),
    (re.compile(r"(?<!\w)في(?!\w)"), "in"),
]

# Keyword arguments - حجج الكلمات المفتاحية
_KW_ALIASES = {
    "ترميز": "encoding",
    "تأكد_من_ascii": "ensure_ascii",
    "مسافة_بادئة": "indent",
}

# I/O aliases - إدخال/إخراج
_IO_ALIASES = {
    "اقرأ": "_apl_read",
    "اكتب": "_apl_write",
    "اغلق": "_apl_close",
    "طلب": "_apl_fetch",
}
_IO_PATTERN = re.compile("(" + "|".join(_IO_ALIASES.keys()) + r")\s*\(")

# Context Managers - مديرو السياق
_CONTEXT_ALIASES = {
    "مع": "with",
    "داخل": "with",
    "مدير": "contextmanager",
    "مدير_سياق": "contextmanager",
    "دخل": "__enter__",
    "اخرج": "__exit__",
    "دخل_سياق": "__enter__",
    "اخرج_سياق": "__exit__",
    "افتح_سياق": "contextmanager",
    "حرر": "contextmanager",
    "تلقائياً": "finally",
    "تلقائي": "finally",
    "ضمني": "with",
    "ضمنياً": "with",
    "داخل_ملف": "with open",
    "افتح_ملف": "with open",
    "مع_فتح": "with open",
    "مع_ملف": "with open",
    "قفل_ضمني": "with lock",
    "قفل_تلقائي": "with lock",
    "حرر_قفل": "with lock",
    "اتصل_ضمني": "with connection",
    "اتصل_تلقائي": "with connection",
    "مؤقت_ضمني": "with timer",
    "مؤقت_تلقائي": "with timer",
    "كاش_ضمني": "with cache",
    "كاش_تلقائي": "with cache",
    "طابور_ضمني": "with queue",
    "طابور_تلقائي": "with queue",
    "شرط_ضمني": "with condition",
    "شرط_تلقائي": "with condition",
    "إشارة_ضمني": "with semaphore",
    "إشارة_تلقائي": "with semaphore",
    "قفل_دوار": "with lock",
    "قفل_دوار_ضمني": "with lock",
    "قفل_دوار_تلقائي": "with lock",
    "قفل_قراءة": "with rlock",
    "قفل_كتابة": "with wlock",
    "قفل_قراءة_ضمني": "with rlock",
    "قفل_كتابة_ضمني": "with wlock",
    "قفل_قراءة_تلقائي": "with rlock",
    "قفل_كتابة_تلقائي": "with wlock",
    "قفل_مشترك": "with shared_lock",
    "قفل_مشترك_ضمني": "with shared_lock",
    "قفل_مشترك_تلقائي": "with shared_lock",
    "قفل_حصري": "with exclusive_lock",
    "قفل_حصري_ضمني": "with exclusive_lock",
    "قفل_حصري_تلقائي": "with exclusive_lock",
    "قفل_ثنائي": "with binary_lock",
    "قفل_ثنائي_ضمني": "with binary_lock",
    "قفل_ثنائي_تلقائي": "with binary_lock",
    "قفل_متعدد": "with multi_lock",
    "قفل_متعدد_ضمني": "with multi_lock",
    "قفل_متعدد_تلقائي": "with multi_lock",
    "قفل_هرمي": "with hierarchical_lock",
    "قفل_هرمي_ضمني": "with hierarchical_lock",
    "قفل_هرمي_تلقائي": "with hierarchical_lock",
    "قفل_شجري": "with tree_lock",
    "قفل_شجري_ضمني": "with tree_lock",
    "قفل_شجري_تلقائي": "with tree_lock",
    "قفل_قارئ_كاتب": "with rw_lock",
    "قفل_قارئ_كاتب_ضمني": "with rw_lock",
    "قفل_قارئ_كاتب_تلقائي": "with rw_lock",
    "قفل_مرحلة": "with phase_lock",
    "قفل_مرحلة_ضمني": "with phase_lock",
    "قفل_مرحلة_تلقائي": "with phase_lock",
    "قفل_انتقال": "with transition_lock",
    "قفل_انتقال_ضمني": "with transition_lock",
    "قفل_انتقال_تلقائي": "with transition_lock",
    "قفل_تزامن": "with sync_lock",
    "قفل_تزامن_ضمني": "with sync_lock",
    "قفل_تزامن_تلقائي": "with sync_lock",
    "قفل_تزامني": "with sync_lock",
    "قفل_تزامني_ضمني": "with sync_lock",
    "قفل_تزامني_تلقائي": "with sync_lock",
    "قفل_غير_تزامني": "with async_lock",
    "قفل_غير_تزامني_ضمني": "with async_lock",
    "قفل_غير_تزامني_تلقائي": "with async_lock",
    "قفل_تزامني_مخصص": "with custom_sync_lock",
    "قفل_تزامني_مخصص_ضمني": "with custom_sync_lock",
    "قفل_تزامني_مخصص_تلقائي": "with custom_sync_lock",
    "قفل_غير_تزامني_مخصص": "with custom_async_lock",
    "قفل_غير_تزامني_مخصص_ضمني": "with custom_async_lock",
    "قفل_غير_تزامني_مخصص_تلقائي": "with custom_async_lock",
    "قفل_تزامني_عام": "with global_sync_lock",
    "قفل_تزامني_عام_ضمني": "with global_sync_lock",
    "قفل_تزامني_عام_تلقائي": "with global_sync_lock",
    "قفل_غير_تزامني_عام": "with global_async_lock",
    "قفل_غير_تزامني_عام_ضمني": "with global_async_lock",
    "قفل_غير_تزامني_عام_تلقائي": "with global_async_lock",
    "قفل_تزامني_محلي": "with local_sync_lock",
    "قفل_تزامني_محلي_ضمني": "with local_sync_lock",
    "قفل_تزامني_محلي_تلقائي": "with local_sync_lock",
    "قفل_غير_تزامني_محلي": "with local_async_lock",
    "قفل_غير_تزامني_محلي_ضمني": "with local_async_lock",
    "قفل_غير_تزامني_محلي_تلقائي": "with local_async_lock",
    "قفل_تزامني_جلسة": "with session_sync_lock",
    "قفل_تزامني_جلسة_ضمني": "with session_sync_lock",
    "قفل_تزامني_جلسة_تلقائي": "with session_sync_lock",
    "قفل_غير_تزامني_جلسة": "with session_async_lock",
    "قفل_غير_تزامني_جلسة_ضمني": "with session_async_lock",
    "قفل_غير_تزامني_جلسة_تلقائي": "with session_async_lock",
    "قفل_تزامني_مستخدم": "with user_sync_lock",
    "قفل_تزامني_مستخدم_ضمني": "with user_sync_lock",
    "قفل_تزامني_مستخدم_تلقائي": "with user_sync_lock",
    "قفل_غير_تزامني_مستخدم": "with user_async_lock",
    "قفل_غير_تزامني_مستخدم_ضمني": "with user_async_lock",
    "قفل_غير_تزامني_مستخدم_تلقائي": "with user_async_lock",
    "قفل_تزامني_قاعدة": "with db_sync_lock",
    "قفل_تزامني_قاعدة_ضمني": "with db_sync_lock",
    "قفل_تزامني_قاعدة_تلقائي": "with db_sync_lock",
    "قفل_غير_تزامني_قاعدة": "with db_async_lock",
    "قفل_غير_تزامني_قاعدة_ضمني": "with db_async_lock",
    "قفل_غير_تزامني_قاعدة_تلقائي": "with db_async_lock",
    "قفل_تزامني_ملف": "with file_sync_lock",
    "قفل_تزامني_ملف_ضمني": "with file_sync_lock",
    "قفل_تزامني_ملف_تلقائي": "with file_sync_lock",
    "قفل_غير_تزامني_ملف": "with file_async_lock",
    "قفل_غير_تزامني_ملف_ضمني": "with file_async_lock",
    "قفل_غير_تزامني_ملف_تلقائي": "with file_async_lock",
    "قفل_تزامني_شبكة": "with network_sync_lock",
    "قفل_تزامني_شبكة_ضمني": "with network_sync_lock",
    "قفل_تزامني_شبكة_تلقائي": "with network_sync_lock",
    "قفل_غير_تزامني_شبكة": "with network_async_lock",
    "قفل_غير_تزامني_شبكة_ضمني": "with network_async_lock",
    "قفل_غير_تزامني_شبكة_تلقائي": "with network_async_lock",
    "قفل_تزامني_نظام": "with system_sync_lock",
    "قفل_تزامني_نظام_ضمني": "with system_sync_lock",
    "قفل_تزامني_نظام_تلقائي": "with system_sync_lock",
    "قفل_غير_تزامني_نظام": "with system_async_lock",
    "قفل_غير_تزامني_نظام_ضمني": "with system_async_lock",
    "قفل_غير_تزامني_نظام_تلقائي": "with system_async_lock",
    "قفل_تزامني_مخصص_عام": "with custom_global_sync_lock",
    "قفل_تزامني_مخصص_عام_ضمني": "with custom_global_sync_lock",
    "قفل_تزامني_مخصص_عام_تلقائي": "with custom_global_sync_lock",
    "قفل_غير_تزامني_مخصص_عام": "with custom_global_async_lock",
    "قفل_غير_تزامني_مخصص_عام_ضمني": "with custom_global_async_lock",
    "قفل_غير_تزامني_مخصص_عام_تلقائي": "with custom_global_async_lock",
    "قفل_تزامني_مخصص_محلي": "with custom_local_sync_lock",
    "قفل_تزامني_مخصص_محلي_ضمني": "with custom_local_sync_lock",
    "قفل_تزامني_مخصص_محلي_تلقائي": "with custom_local_sync_lock",
    "قفل_غير_تزامني_مخصص_محلي": "with custom_local_async_lock",
    "قفل_غير_تزامني_مخصص_محلي_ضمني": "with custom_local_async_lock",
    "قفل_غير_تزامني_مخصص_محلي_تلقائي": "with custom_local_async_lock",
    "قفل_تزامني_مخصص_جلسة": "with custom_session_sync_lock",
    "قفل_تزامني_مخصص_جلسة_ضمني": "with custom_session_sync_lock",
    "قفل_تزامني_مخصص_جلسة_تلقائي": "with custom_session_sync_lock",
    "قفل_غير_تزامني_مخصص_جلسة": "with custom_session_async_lock",
    "قفل_غير_تزامني_مخصص_جلسة_ضمني": "with custom_session_async_lock",
    "قفل_غير_تزامني_مخصص_جلسة_تلقائي": "with custom_session_async_lock",
    "قفل_تزامني_مخصص_مستخدم": "with custom_user_sync_lock",
    "قفل_تزامني_مخصص_مستخدم_ضمني": "with custom_user_sync_lock",
    "قفل_تزامني_مخصص_مستخدم_تلقائي": "with custom_user_sync_lock",
    "قفل_غير_تزامني_مخصص_مستخدم": "with custom_user_async_lock",
    "قفل_غير_تزامني_مخصص_مستخدم_ضمني": "with custom_user_async_lock",
    "قفل_غير_تزامني_مخصص_مستخدم_تلقائي": "with custom_user_async_lock",
    "قفل_تزامني_مخصص_قاعدة": "with custom_db_sync_lock",
    "قفل_تزامني_مخصص_قاعدة_ضمني": "with custom_db_sync_lock",
    "قفل_تزامني_مخصص_قاعدة_تلقائي": "with custom_db_sync_lock",
    "قفل_غير_تزامني_مخصص_قاعدة": "with custom_db_async_lock",
    "قفل_غير_تزامني_مخصص_قاعدة_ضمني": "with custom_db_async_lock",
    "قفل_غير_تزامني_مخصص_قاعدة_تلقائي": "with custom_db_async_lock",
    "قفل_تزامني_مخصص_ملف": "with custom_file_sync_lock",
    "قفل_تزامني_مخصص_ملف_ضمني": "with custom_file_sync_lock",
    "قفل_تزامني_مخصص_ملف_تلقائي": "with custom_file_sync_lock",
    "قفل_غير_تزامني_مخصص_ملف": "with custom_file_async_lock",
    "قفل_غير_تزامني_مخصص_ملف_ضمني": "with custom_file_async_lock",
    "قفل_غير_تزامني_مخصص_ملف_تلقائي": "with custom_file_async_lock",
    "قفل_تزامني_مخصص_شبكة": "with custom_network_sync_lock",
    "قفل_تزامني_مخصص_شبكة_ضمني": "with custom_network_sync_lock",
    "قفل_تزامني_مخصص_شبكة_تلقائي": "with custom_network_sync_lock",
    "قفل_غير_تزامني_مخصص_شبكة": "with custom_network_async_lock",
    "قفل_غير_تزامني_مخصص_شبكة_ضمني": "with custom_network_async_lock",
    "قفل_غير_تزامني_مخصص_شبكة_تلقائي": "with custom_network_async_lock",
    "قفل_تزامني_مخصص_نظام": "with custom_system_sync_lock",
    "قفل_تزامني_مخصص_نظام_ضمني": "with custom_system_sync_lock",
    "قفل_تزامني_مخصص_نظام_تلقائي": "with custom_system_sync_lock",
    "قفل_غير_تزامني_مخصص_نظام": "with custom_system_async_lock",
    "قفل_غير_تزامني_مخصص_نظام_ضمني": "with custom_system_async_lock",
    "قفل_غير_تزامني_مخصص_نظام_تلقائي": "with custom_system_async_lock",
}
_CONTEXT_PATTERN = re.compile("(" + "|".join(_CONTEXT_ALIASES.keys()) + r")\s*\(")
